server:
  port: 7777
spring:
  application:
    name: registerServerWithEureka-01
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}